jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/app

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - restore_cache:
          keys:
            - app-source-{{ .Branch }}-{{ .Revision }}
            - app-source-{{ .Branch }}-
            - app-source-

      - checkout
      - save_cache:
          key: app-source-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/app

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle clean build test
      - save_cache:
          key: v1-build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - build
            - Dockerfile

  dokku_deploy:
    working_directory: ~/app
    docker:
      - image: alpine:3.6
    steps:
      - checkout
      - run: apk add --no-cache git openssh-client
      - run: mkdir -p ~/.ssh
      - run: ssh-keyscan "techaid.ju.ma" >> ~/.ssh/known_hosts
      - run: git push ssh://dokku@techaid.ju.ma/api HEAD:refs/heads/master

version: 2.1
workflows:
  version: 2
  ci_workflow:
    jobs:
      - build
      - dokku_deploy:
          context: global
          requires:
            - build
          filters:
            branches:
              only:
                - master
